package sys.modelo;
// Generated 16/09/2023 13:26:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String marca;
     private String categoria;
     private String ciudad;
     private int cantidad;
     private BigDecimal precio;

    public Inventario() {
    }

    public Inventario(String nombre, String marca, String categoria, String ciudad, int cantidad, BigDecimal precio) {
       this.nombre = nombre;
       this.marca = marca;
       this.categoria = categoria;
       this.ciudad = ciudad;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


