package sys.modelo;
// Generated 16/09/2023 13:26:20 by Hibernate Tools 4.3.1



/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private Integer idUsuario;
     private String usuario;
     private String password;

    public Sesion() {
    }

    public Sesion(String usuario, String password) {
       this.usuario = usuario;
       this.password = password;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


